---
namespace: "python"
createNamespace: true
replicaCount: 1

image:
  repository: romanolitvinov/watcher_bot
  tag: 1
  pullPolicy: Always

env:
  LOG_LEVEL: "INFO"
  LOG_FILE: "/tmp/bot.log"
  RESTART_NOTIFICATION: "true"

secrets:
  TOKEN: "CHANGE_TOKEN"
  ALLOWED_USERS: "CHANGE_ALLOWED_USERS"
