---
namespace: "python"
createNamespace: true
replicaCount: 1

image:
  repository: romanolitvinov/watcher_bot
  tag: 1
  pullPolicy: Always

env:
  LOG_LEVEL: "DEBUG"
  RESTART_NOTIFICATION: "true"

secrets:
  TOKEN: 345345345:AAHsMFGPIOWZfdklfgjljsd-sdfsdg
  ALLOWED_USERS: 6153020341HELLO!
