---
version: '3.7'

services:
    python_telegram:
      build:
        context: ./
      container_name: watcher_bot
      image: romanolitvinov/watcherbot:1
      restart: no

      environment:
        - TOKEN=CHANGE_TOKEN
        - ALLOWED_USERS=CHANGE_ALLOWED_USERS
