---
version: '3.7'

services:
    python_telegram:
      build:
        context: ./
      container_name: watcher_bot
      image: q163i/watcherbot:1
      restart: no

      environment:
        # Example bot token
        - TOKEN=7105555008:adgj09u0asdfsf33alskfas
        # Admins chat_ID
        - ALLOWED_USERS=6242555555
