---
version: '3.7'

services:
    python_telegram:
      build:
        context: ./
      container_name: watcher_bot
      image: romanolitvinov/watcherbot:1
      restart: no

      environment:
        - TOKEN=345345345:AAHsMFGPIOWZfdklfgjljsd-sdfsdg
        - ALLOWED_USERS=6153020341HELLO!
