---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "python.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    project: {{ .Values.projectName }}
spec:
  tls:
  - hosts:
    - {{ .Chart.Name }}.local
    secretName: watcher-bot-tls
  rules:
    - host: "my-host"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "python.fullname" . }}
                port:
                  number: {{ .Values.service.port }}