---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
