---
name: GitHub Actions for watcher_bot project

on:
  push:
    branches: [ "main" ]

jobs:
  DockerMultiBuildAndPush:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: ['linux/amd64, linux/arm64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: romanolitvinov
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: |
          romanolitvinov/watcher_bot:latest
        platforms: ${{ matrix.platform }}

#  CheckHelmValidatorScript:
#    needs:
#      - DockerMultiBuildAndPush
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Login to DockerHub
#      uses: docker/login-action@v3
#      with:
#        username: romanolitvinov
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    - name: Check Helm Charts
#      run: |
#        docker run -v $(pwd)/instances:/instances romanolitvinov/d2d_helm_validator:latest

  NotifySuccessBuild:
    needs:
#      - CheckHelmValidatorScript
      - DockerMultiBuildAndPush
    runs-on: ubuntu-latest

    steps:
      - name: watcher_bot send message (success build)
        run: "docker run -e TOKEN=$TOKEN -e ALLOWED_USERS=$ALLOWED_USERS romanolitvinov/watcher_bot:latest python3 /app/bot/SimpleMessage.py infoDeploySuccess --text 'GitHub: d2d. Build and push success'"
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}

  NotifyFailureBuild:
    needs:
#      - CheckHelmValidatorScript
      - DockerMultiBuildAndPush
    runs-on: ubuntu-latest
    if: failure()

    steps:
      - name: watcher_bot send message (fail build)
        run: "docker run -e TOKEN=$TOKEN -e ALLOWED_USERS=$ALLOWED_USERS romanolitvinov/watcher_bot:latest python3 /app/bot/SimpleMessage.py infoDeployFail --text 'GitHub: d2d. Build and push failed'"
        env:
          TOKEN: ${{ secrets.TOKEN }}
          ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}
