---
name: GitHub Actions for watcher_bot project

on:
  push:
    branches: [ "main" ]

jobs:
  DockerMultiBuildAndPush:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: ['linux/amd64, linux/arm64']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: romanolitvinov
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: |
          romanolitvinov/watcher_bot:latest
        platforms: ${{ matrix.platform }}

#  CheckHelmValidatorScript:
#    needs:
#      - DockerMultiBuildAndPush
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Login to DockerHub
#      uses: docker/login-action@v3
#      with:
#        username: romanolitvinov
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#    - name: Check Helm Charts
#      run: |
#        docker run -v $(pwd)/instances:/instances romanolitvinov/d2d_helm_validator:latest

  NotifySuccessBuild:
    needs:
#      - CheckHelmValidatorScript
      - DockerMultiBuildAndPush
    runs-on: ubuntu-latest
    env:
      GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Success: Notify Message"
        run: 'docker run -e "GITHUB_BUILD_STATUS=$GITHUB_BUILD_STATUS" -e "TOKEN=$TOKEN" -e "ALLOWED_USERS=$ALLOWED_USERS" -e "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" -e "GITHUB_REF=$GITHUB_REF" -e "GITHUB_ACTOR=$GITHUB_ACTOR" -e "GITHUB_COMMIT_MESSAGE=$GITHUB_COMMIT_MESSAGE" -e "GITHUB_RUN_ID=$GITHUB_RUN_ID" romanolitvinov/watcher_bot:latest python3 /app/bot/SimpleMessage.py infoDeploySuccess'
        env:
          GITHUB_BUILD_STATUS: "🔝Build Success"
          TOKEN: "${{ secrets.TOKEN }}"
          ALLOWED_USERS: "${{ secrets.ALLOWED_USERS }}"

  NotifyFailureBuild:
    needs:
#      - CheckHelmValidatorScript
      - DockerMultiBuildAndPush
    runs-on: ubuntu-latest
    if: failure()
    env:
      GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Fail: Notify Message"
        run: 'docker run -e "GITHUB_BUILD_STATUS=$GITHUB_BUILD_STATUS" -e "TOKEN=$TOKEN" -e "ALLOWED_USERS=$ALLOWED_USERS" -e "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" -e "GITHUB_REF=$GITHUB_REF" -e "GITHUB_ACTOR=$GITHUB_ACTOR" -e "GITHUB_COMMIT_MESSAGE=$GITHUB_COMMIT_MESSAGE" -e "GITHUB_RUN_ID=$GITHUB_RUN_ID" romanolitvinov/watcher_bot:latest python3 /app/bot/SimpleMessage.py infoDeployFail'
        env:
          GITHUB_BUILD_STATUS: "⚠️Build Fail"
          TOKEN: "${{ secrets.TOKEN }}"
          ALLOWED_USERS: "${{ secrets.ALLOWED_USERS }}"
